---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
#    caBundle: ""
    url: https://172.16.1.242:9443/mutate-core-crd-lixueduan-com-v1-application
#    service:
#      name: webhook-service
#      namespace: system
#      path: /mutate-core-crd-lixueduan-com-v1-application
  failurePolicy: Fail
  name: mapplication-v1.lixueduan.com
  rules:
  - apiGroups:
    - core.crd.lixueduan.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
#    caBundle: ""
    url: https://172.16.1.242:9443/validate-core-crd-lixueduan-com-v1-application
#    service:
#      name: webhook-service
#      namespace: system
#      path: /validate-core-crd-lixueduan-com-v1-application
  failurePolicy: Fail
  name: vapplication-v1.lixueduan.com
  rules:
  - apiGroups:
    - core.crd.lixueduan.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
